config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
end

app/views/layouts/_footer.html.erb
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

<div class="footer">
  <p>&copy; Made by Carlos Ferreira - 2017</p>
  <a class="logo"><%= image_tag "logo.svg" %></a>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "myRecipes", root_path, class: "btn btn-lg btn-primary", id: "logo" %>
    <ul class="nav_ul_item">
      <li class="dropdown">
        <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          Styles <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Style.all.each do |style| %>
              <li><%= link_to style.name, style_path(style) %></li>
            <% end %>
            <% if logged_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to(new_style_path) do %>
                  New style
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
    </ul>
    <ul class="nav_ul_item">
      <li class="dropdown">
        <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          Ingredients <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Ingredient.all.each do |ingredient| %>
              <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
            <% end %>
            <% if logged_in? %>
              <li class='divider'></li>
              <li>
                <%= link_to(new_ingredient_path) do %>
                  New Ingredient
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
    </ul>
    <% if logged_in? %>
      <div class="nav_ul_item">
        <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-info" %>
      </div>
      <ul class="nav_item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.name %> <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "View Profile", chef_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      </ul>
    <% else %>
        <div class="nav_item">
          <%= link_to "Log in", login_path, class: "btn btn-default btn-success" %>
        </div>
    <% end %>
  </div>
</header>

app/views/layouts/_navigation1.html.erb
<nav class="navbar-custom" role="navigation">
  <div class="custom-container">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>
    <div class="navbar-brand logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Recipes", recipes_path %></li>
        
        <li>
          <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            Styles <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Style.all.each do |style| %>
              <li><%= link_to style.name, style_path(style) %></li>
            <% end %>
            <% if logged_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to(new_style_path) do %>
                  New style
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
        
        <li>
        <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
          Ingredients <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Ingredient.all.each do |ingredient| %>
              <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
            <% end %>
            <% if logged_in? %>
              <li class='divider'></li>
              <li>
                <%= link_to(new_ingredient_path) do %>
                  New Ingredient
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
      
      <% if logged_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.name %> <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "View Profile", chef_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      </ul>
      
      <div class="nav navbar-nav navbar-right">
        <li><%= link_to "New Recipe", new_recipe_path %></li>
      </div>
      
    <% else %>
        <div class="nav navbar-nav navbar-right">
          <li><%= link_to "Log in", login_path %></li>
        </div>
    <% end %>
    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<section class="hero-image">
  <div class="hero-image__copy">
    <h1 class="title">Welcome to BestChefs</h1>
    <h2 class= "subtitle">where your food dreams</br>will come true.</h2>
    <%= link_to "Sign Up Now!", register_path, class: 'hero-image__button'%>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BestChef</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation1' %>
  
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    
  </div>
  
  <%= render 'layouts/footer' %>

</body>
</html>